#!/usr/bin/env bash

BT_API=api.bintray.com
BT_SUBJECT=dermetfan
BT_REPO=generic
BT_PACKAGE=libgdx-utils

api ( ) {
	echo https://$BT_SUBJECT:$BT_API_KEY@$BT_API
}

upload ( ) {
	FILE=$1
	BT_VERSION=$2
	BT_FILEPATH=$3
	BT_PUBLISH=$4
	
	curl -T $FILE `api`/content/$BT_SUBJECT/$BT_REPO/$BT_PACKAGE/$BT_VERSION/$BT_FILEPATH?publish=$BT_PUBLISH
}

uploadDir ( ) {
	DIR=$1
	BT_VERSION=$2
	BT_PUBLISH=$3
	
	for file in $DIR/*
	do
		upload $file $BT_VERSION $BT_PACKAGE/$BT_VERSION/`basename $file` $BT_PUBLISH
	done
}

ensure_version ( ) {
	BT_VERSION=$1
	
	if [ -z 'curl `api`/packages/$BT_SUBJECT/$BT_REPO/$BT_PACKAGE/versions/$BT_VERSION | grep -o "\"name\":\"[0-9.]*\"" | grep -o "[0-9.]*"' ]
		then
			echo "Creating version $BT_VERSION in package $BT_PACKAGE..."
			curl -X POST "`api`/packages/$BT_SUBJECT/$BT_REPO/$BT_PACKAGE/versions" -H "Content-Type: application/json" -d "{\"name\": \"$BT_VERSION\", \"desc\": \"`cat RELEASE\ NOTES`\"}"
	fi
}

DIR=$1
VERSION=$2

if [ -n "$3" ]
	then
		BT_API_KEY=$3
fi

if [ -n "$4" ]
	then
		BT_PUBLISH=$4
	else
		BT_PUBLISH=1
fi

ensure_version $VERSION
uploadDir $DIR $VERSION $BT_PUBLISH
