#!/usr/bin/env bash

BT_API=api.bintray.com
BT_SUBJECT=dermetfan
BT_REPO=libgdx-utils

subject ( ) {
	echo "https://$BT_SUBJECT:$BT_API_KEY@$BT_API/content/$BT_SUBJECT"
}

repo ( ) {
	echo "`subject`/$BT_REPO"
}

upload ( ) {
	FILE=$1
	BT_PACKAGE=$2
	BT_VERSION=$3
	BT_FILEPATH=$4
	BT_PUBLISH=$5
	
	curl -T $FILE "`repo`/$BT_PACKAGE/$BT_VERSION/$BT_FILEPATH?publish=$BT_PUBLISH"
}

uploadDir ( ) {
	DIR=$1
	BT_PACKAGE=$2
	BT_VERSION=$3
	BT_PUBLISH=$4
	
	for file in $DIR/*
	do
		upload $file $BT_PACKAGE $BT_VERSION `basename $file` $BT_PUBLISH
	done
}

publish ( ) {
	BT_PACKAGE=$1
	BT_VERSION=$2
	BT_DISCARD=$3
	
	curl -X POST "`repo`/$BT_PACKAGE/$BT_VERSION/publish?discard=$BT_DISCARD"
}

if [ -n "$1" ]
	then
		BT_API_KEY=$1
fi

uploadDir build/libs libgdx-utils `cat VERSION` 1
uploadDir box2d/build/libs libgdx-utils-box2d `cat box2d/VERSION` 1
